#kind: PersistentVolume
#apiVersion: v1
#metadata:
#  name: mongodb-pv-volume
#  labels:
#    type: local
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 2Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/home/uany/mongodb/u5gc/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
spec:
  storageClassName: mongodb-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
