apiVersion: v1
kind: Service
metadata:
  labels:
    app: u5gc-pcf
  name: u5gc-pcf
spec:
  type: ClusterIP
  ports:
  - name: u5gc-pcf
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: u5gc-pcf
