kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - 01_pcf-sa.yaml
  - 02_pcf-rbac.yaml
  - 03_pcf-service.yaml
  - 04_pcf-deployment.yaml

secretGenerator:
- name: u5gc-pcf-tls-secret
  files:
  - cert/pcf.pem
  - cert/pcf.key
  type: "Opaque"

configMapGenerator:
- name: u5gc-pcf-config
  files:
  - config/pcfcfg.yaml