info:
  version: 1.0.1
  description: PCF initial local configuration

configuration:
  pcfName: PCF
  sbi:
    scheme: http
    registerIPv4: u5gc-pcf
    bindingIPv4: 0.0.0.0
    port: 8000
    tls:
      pem: ./config/TLS/pcf.pem
      key: ./config/TLS/pcf.key
  timeFormat: 2019-01-02 15:04:05
  defaultBdtRefId: BdtPolicyId-
  nrfUri: http://u5gc-scp-nrf:8000
  serviceList:
    - serviceName: npcf-am-policy-control
    - serviceName: npcf-smpolicycontrol
      suppFeat: 3
    - serviceName: npcf-bdtpolicycontrol
    - serviceName: npcf-policyauthorization
      suppFeat: 3
    - serviceName: npcf-eventexposure
    - serviceName: npcf-ue-policy-control
  mongodb:
    name: u5gc
    url: mongodb://u5gc-mongodb:27017
  locality: area1

logger:
  PCF:
    debugLevel: trace
    ReportCaller: false