apiVersion: apps/v1
kind: Deployment
metadata:
  name: u5gc-webui
  labels:
    app: u5gc-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: u5gc-webui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: u5gc-webui
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: u5gc-webui
        image: webui_image
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
        volumeMounts:
        - name: u5gc-webui-config
          mountPath: /app/config
        - name: tz-seoul
          mountPath: /etc/localtime
        ports:
        - containerPort: 5000
          name: u5gc-webui
          protocol: TCP
        args: [/bin/sh, -c, '/app/webui -c /app/config/webuicfg.yaml']
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: u5gc-webui-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: u5gc-webui-config
          configMap:
            name: u5gc-webui-config
        - name: tz-seoul
          hostPath: 
            path: /usr/share/zoneinfo/Asia/Seoul
