kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- 01_webui-sa.yaml
- 02_webui-rbac.yaml
- 03_webui-service.yaml
- 04_webui-deployment.yaml

configMapGenerator:
- name: u5gc-webui-config
  files:
  - config/webuicfg.yaml