apiVersion: apps/v1
kind: Deployment
metadata:
  name: u5gc-upf
  labels:
    app: u5gc-upf
    sliceidx: 6d3d79da-f781-4cd9-813a-dbdad01e01c0
  annotations:
    u5gc.org/nssi-id: '27394d25-dbf5-428e-8fc3-f5b2add67115'
    u5gc.org/nsi-ids: '[ { "id": "4e6db941-47d6-4fce-9c71-f7eb35a75d03" } ]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: u5gc-upf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: u5gc-upf
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: u5gc-upf
        image: upf_image
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN", "NET_RAW", "NET_BIND_SERVICE", "SYS_TIME"]
        volumeMounts:
        - name: u5gc-upf-config
          mountPath: /app/config
        - mountPath: /dev/net/tun
          name: tun-devdir
        - name: tz-seoul
          mountPath: /etc/localtime
        ports:
        - containerPort: 2152
          name: if-n3
          protocol: UDP
        - containerPort: 8805
          name: if-n4
          protocol: UDP
        args: [/bin/sh, -c, '/bin/sh /app/config/upf-iptables.sh && /app/free5gc-upfd -c /app/config/upfcfg.yaml']
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: u5gc-upf-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: u5gc-upf-config
          configMap:
            name: u5gc-upf-config
        - name: tun-devdir
          hostPath:
            path: /dev/net/tun
        - name: tz-seoul
          hostPath: 
            path: /usr/share/zoneinfo/Asia/Seoul
