apiVersion: v1
kind: Service
metadata:
  labels:
    app: u5gc-smf
  name: u5gc-smf
spec:
  type: NodePort
  ports:
  - name: u5gc-smf-sbi
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: u5gc-smf-n4
    nodePort: 8805
    port: 8805
    protocol: UDP
    targetPort: 8805
  selector:
    app: u5gc-smf
