apiVersion: v1
kind: Service
metadata:
  labels:
    app: u5gc-udm
  name: u5gc-udm
spec:
  type: ClusterIP
  ports:
  - name: u5gc-udm
    port: 8001
    protocol: TCP
    targetPort: 8001
  - name: u5gc-udr
    port: 8002
    protocol: TCP
    targetPort: 8002
  - name: u5gc-ausf
    port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    app: u5gc-udm
