apiVersion: apps/v1
kind: Deployment
metadata:
  name: u5gc-udm
  labels:
    app: u5gc-udm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: u5gc-udm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: u5gc-udm
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: u5gc-udm
          image: udm_image
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          volumeMounts:
            - name: u5gc-udm-config
              mountPath: /app/config
            - name: u5gc-udm-cert
              mountPath: /app/config/TLS
            - name: u5gc-stats
              mountPath: /app/stats
            - name: tz-seoul
              mountPath: /etc/localtime
          ports:
          - containerPort: 8001
            name: u5gc-udm
            protocol: TCP
          args: [/bin/sh, -c, '/app/udm -c /app/config/udmcfg.yaml']
        - name: u5gc-udr
          image: udr_image
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          volumeMounts:
            - name: u5gc-udr-config
              mountPath: /app/config
            - name: u5gc-udr-cert
              mountPath: /app/config/TLS
            - name: u5gc-stats
              mountPath: /app/stats
            - name: tz-seoul
              mountPath: /etc/localtime
          ports:
          - containerPort: 8002
            name: u5gc-udr
            protocol: TCP
          args: [/bin/sh, -c, '/app/udr -c /app/config/udrcfg.yaml']
        - name: u5gc-ausf
          image: ausf_image
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - name: u5gc-ausf-config
              mountPath: /app/config
            - name: u5gc-ausf-cert
              mountPath: /app/config/TLS
            - name: u5gc-stats
              mountPath: /app/stats
            - name: tz-seoul
              mountPath: /etc/localtime
          ports:
          - containerPort: 8003
            name: u5gc-ausf
            protocol: TCP
          args: [/bin/sh, -c, '/app/ausf -c /app/config/ausfcfg.yaml']
        - name: "uem-emsubagt"
          image: camel.uangel.com:5000/uemsub/uemsub:v1.0.1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 512Mi
          command:
            - 'sh'
            - '-c'
            - >-
              echo ''Setting config file''
              && cp /tmp/data/* /home/app/data/.
              && /home/app/bin/uem
          ports:
            - containerPort: 9292
          env:
            - name: UEM_CONFIG_FILE
              value: "/home/app/data/uemsub.conf"
            - name: UASYS_HOME
              value: "/home/app"
            - name: MYSQL_ADDR
              value: "mariadb.ucdb.svc.cluster.local"
            - name: MYSQL_PORT
              value: "3306"
            - name: EM_SERVICE
              value: "ems-uem"
            - name: EM_HTTP_PORT
              value: "9191"
            - name: MY_GROUP
              value: "UDM_UDR_AUSF"
            - name: TRACE_ENABLED
              value: "false"
          volumeMounts:
            - name: u5gc-stats
              mountPath: /app/stat
            - name: data-volume
              mountPath: /tmp/data
            - name: tz-seoul
              mountPath: /etc/localtime
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: u5gc-udm-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: u5gc-udm-cert
          secret:
            secretName: u5gc-udm-tls-secret
        - name: u5gc-udr-cert
          secret:
            secretName: u5gc-udr-tls-secret
        - name: u5gc-ausf-cert
          secret:
            secretName: u5gc-ausf-tls-secret
        - name: u5gc-udm-config
          configMap:
            name: u5gc-udm-config
        - name: u5gc-udr-config
          configMap:
            name: u5gc-udr-config
        - name: u5gc-ausf-config
          configMap:
            name: u5gc-ausf-config
        - name: u5gc-stats
          emptyDir: {}
        - name: data-volume
          configMap:
            name: uemsub-data
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
