apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/udm


images:
- name: udm_image
  newName: camel.uangel.com:5000/u5gc/udm
  newTag: "v0.311"
- name: udr_image
  newName: camel.uangel.com:5000/u5gc/udr
  newTag: "v0.311"
- name: ausf_image
  newName: camel.uangel.com:5000/u5gc/ausf
  newTag: "v0.311"

patchesStrategicMerge:
- 04_udm-deployment.yaml

configMapGenerator:
- name: u5gc-udm-config
  behavior: replace
  files:
  - config/udmcfg.yaml
- name: u5gc-udr-config
  behavior: replace
  files:
  - config/udrcfg.yaml
- name: u5gc-ausf-config
  behavior: replace
  files:
  - config/ausfcfg.yaml
- name: uemsub-data
  files:
  - config/em_exporter.xml
  - config/uem_logger.conf
  - config/uemsub.conf


# patches:
# - patch: |-
#     - op: add
#       path: /spec/template/spec/nodeSelector
#       value: {kubernetes.io/hostname: mec-tb-worker}
#   target:
#     kind: Deployment
#     labelSelector: "app=u5gc-udm"









namespace: u5gc
