---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: u5gc-mongodb
  name: u5gc-mongodb
spec:
  type: ClusterIP
  ports:
  - name: u5gc-mongodb
    port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: u5gc-mongodb
