info:
  version: 1.0.2
  description: AUSF initial local configuration

modules:
  - ulib.Defaults

configuration:
  sbi:
    scheme: http
    registerIPv4: u5gc-udm
    bindingIPv4: 0.0.0.0
    port: 8003
    tls: # the local path of TLS key
      pem: ./config/TLS/ausf.pem # AUSF TLS Certificate
      key: ./config/TLS/ausf.key # AUSF TLS Private key
  serviceNameList:
    - nausf-auth
  nrfUri: http://u5gc-scp-nrf:8000
  plmnSupportList:
    - mcc: 208
      mnc: 93
    - mcc: 123
      mnc: 45
  groupId: ausfGroup001  

logger:
  AUSF:
    debugLevel: trace
    ReportCaller: false

# statistics item configuration
statistic:
  registry: "default"
  items:
    call: TransactionTimer
    db: TransactionTimer

# metrics reporter configuration
metric:
  default:
    reporters:
      # - class: "logger"
      #   logger: default
      #   logging-changed-only: true
      #   interval: 10s
      - class: "csv"
        file-path: "/app/stats/ausf"
        backup-previous: true
        interval: 1s
        counter:
          use: true
        transaction-request:
          use: true
        transaction-response:
          use: true

# ulib trace configuration
# trace:
#   default-service-name: "AUSF"
#   config-path: "/app/HOME/data/jaegertrace"

# ulib logrus configuration
logrus:
  format: "text"
  print-caller: true
#config-file: "{{.AUSF_LOGGER_PATH}}"
  config-file:
    loggers:
      root:
        level: INFO
        appender:
          - console
    appenders:
      console:
        format: text
        class: Console
        print-caller: "true"
