info:
  version: 1.0.1
  description: UDR initial local configuration

modules:
  - ulib.Defaults

configuration:
  sbi:
    scheme: http
    registerIPv4: u5gc-udm
    bindingIPv4: 0.0.0.0
    port: 8002
    tls: # the local path of TLS key
      pem: ./config/TLS/udr.pem # UDR TLS Certificate
      key: ./config/TLS/udr.key # UDR TLS Private key
  mongodb:
    name: u5gc
    url: mongodb://u5gc-mongodb:27017
  nrfUri: http://u5gc-scp-nrf:8000

logger:
  UDR:
    debugLevel: trace
    ReportCaller: false

# statistics item configuration
statistic:
  registry: "default"
  items:
    call: TransactionTimer
    db: TransactionTimer

# metrics reporter configuration
metric:
  default:
    reporters:
      # - class: "logger"
      #   logger: default
      #   logging-changed-only: true
      #   interval: 10s
      - class: "csv"
        file-path: "/app/stats/udr"
        backup-previous: true
        interval: 1s
        counter:
          use: true
        transaction-request:
          use: true
        transaction-response:
          use: true

# ulib trace configuration
# trace:
#   default-service-name: "UDR"
#   config-path: "/app/HOME/data/jaegertrace"

# ulib logrus configuration
logrus:
  format: "text"
  print-caller: true
#config-file: "{{.UDR_LOGGER_PATH}}"
  config-file:
    loggers:
      root:
        level: INFO
        appender:
          - console
    appenders:
      console:
        format: text
        class: Console
        print-caller: "true"
